### ISSUE TITLE
Type error undefined #newbieCoderQuestion

### ISSUE THREAD

**Issue by Askthemoon** [lelouchB/ai-job-description#1]
Hi lelouchB! Thank you for doing this tutorial on freecodecamp. I was looking for exactly this usecase with nextjs, and as a beginner in coding this is perfect:-)

I have (newbie) question - and hope you might be able to help: 

- I keep getting "undefined" and have had troubles debugging it (see image below). 

- I basically copied the code straight from the tutorial - also tried forking it from your repo, and get the same errors. 

- I do get a response via the API, but the Setjobdescription seem to stay undefined.

- My working theory is that it is the prompt that errors, and therefore doesn't respond. FYI I do have a private API key for OpenAI. 
 
<img width="975" alt="image" src="https://user-images.githubusercontent.com/99611482/214954646-49a2084d-7fc5-491c-a3f4-e416396238a8.png">

Thanks in advance if you take the time to read this.
Kind regards,
Aske

**Comment by lelouchB** [comment]
Hey @Askthemoon 
Just to confirm, the `console.log(data)` line is working and the output is the response from the API ?

Can you share what `console.log(data)` returns

**Comment by Askthemoon** [comment]
Hi @lelouchB Thank you very much for getting back to me on this. Yeah okay, so it doesn't work with console.log(data). 

See the attached image for the error message:
![image](https://user-images.githubusercontent.com/99611482/215164381-4ab441d6-1bda-4722-be36-9152b15c159f.png)

**Comment by lelouchB** [comment]
Hey @Askthemoon 
If you want, we can set up a short call and debug this. It will be way faster.
Can you please DM me on Twitter if you want to hop on a call?

**Comment by gunjan1909** [comment]
Im facing same problem..
console.log(data) returns a large object
But console.log(data.jobDescription) return undefined

**Comment by lelouchB** [comment]
Hey @gunjan1909 
Can you share that large object

**Comment by gunjan1909** [comment]
> Hey @gunjan1909 Can you share that large object

Sry it was just a typo in name of env variable ... it was resolved

**Comment by lelouchB** [comment]
@gunjan1909 
Glad it was resolved :)

**Comment by Askthemoon** [comment]
Thank you very much, Ash! Problem solved with the kindness of Ash. I mistakenly copied the shortened API-key to openai's API. If you face similar issues out there in the ether then simply generate a new key, and use this instead.
