### ISSUE TITLE
Help me

### ISSUE THREAD

**Issue by cupidarrow0417** [lelouchB/ai-job-description#2]
Of course, your project is perfect.
But I can response data.
I wrote exact API key.
What is it?

**Comment by lelouchB** [comment]
What is the name of the Environment Variable ?

**Comment by cupidarrow0417** [comment]
![image](https://user-images.githubusercontent.com/122076117/215521431-acde4f1b-d75f-4d78-871f-3d5f0f9eb254.png)

**Comment by lelouchB** [comment]
@cupidarrow0417 
This looks good, please delete this image, it reveals your private key

**Comment by lelouchB** [comment]
What is the response from the API ?
Empty ?

**Comment by cupidarrow0417** [comment]
![image](https://user-images.githubusercontent.com/122076117/215521808-33e41101-0039-495e-b881-136a46866a57.png)

**Comment by cupidarrow0417** [comment]
Yes. Empty

**Comment by cupidarrow0417** [comment]
???

**Comment by lelouchB** [comment]
@cupidarrow0417 
Can you regenerate another key and try again with it

**Comment by cupidarrow0417** [comment]
Same.
Can I check through postman?

**Comment by lelouchB** [comment]
Yes, that also works

**Comment by cupidarrow0417** [comment]
Can you share screenshot your postman checking?

**Comment by lelouchB** [comment]
I don't use Postman
We can replace the current API key in code to test

**Comment by cupidarrow0417** [comment]
![image](https://user-images.githubusercontent.com/122076117/215524233-47a38d4c-edf0-4230-8b7f-5569c1ea3d81.png)

**Comment by cupidarrow0417** [comment]
???

**Comment by lelouchB** [comment]
The error is with your Open AI Account, you have used all the free quotas.
You either need to upgrade your Open AI account or create a new account

**Comment by cupidarrow0417** [comment]
An error occurred. If this issue persists please contact us through our help center at help.openai.com.
That error is about that?

**Comment by lelouchB** [comment]
Yes

**Comment by cupidarrow0417** [comment]
How can I upgrade my account?

**Comment by lelouchB** [comment]
https://openai.com/api/pricing/

**Comment by cupidarrow0417** [comment]
Thank you.
How much can I use for free

**Comment by cupidarrow0417** [comment]
I think about 10 questions?

**Comment by cupidarrow0417** [comment]
And never charge?

**Comment by lelouchB** [comment]
Hard to say the number but its much larger than 10, probably in thousands
I would suggest to create another account and use those free credits

**Comment by cupidarrow0417** [comment]
How can I solve phone number.
Duplicate is it ok?

**Comment by lelouchB** [comment]
No, a different number is required

**Comment by lelouchB** [comment]
@cupidarrow0417 
Closing this issue
