### ISSUE TITLE
Help me again!

### ISSUE THREAD

**Issue by cupidarrow0417** [lelouchB/ai-job-description#3]
![image](https://user-images.githubusercontent.com/122076117/215539001-ddba68f7-5e2f-4660-b422-c7e59cd7321b.png)

**Comment by lelouchB** [comment]
Update the Content Type Header 
https://carldesouza.com/how-to-set-content-type-to-application-json-in-postman/

**Comment by cupidarrow0417** [comment]
![image](https://user-images.githubusercontent.com/122076117/215540082-fcfff2f9-3d1f-4752-9a8f-ed54eae10b4f.png)
I did it

**Comment by lelouchB** [comment]
Also need to add Bearer Token in Authorization header

**Comment by cupidarrow0417** [comment]
I did it, Just delete and screenshot because it is secret

**Comment by lelouchB** [comment]
Oh Actually, you have selected wrong Body type
Select binary

**Comment by cupidarrow0417** [comment]
If select binary, select file button so how can I add information?

**Comment by lelouchB** [comment]
Select form data

**Comment by cupidarrow0417** [comment]
Same error

**Comment by lelouchB** [comment]
Raw maybe
I haven't used Postman in long time

**Comment by cupidarrow0417** [comment]
What about chatting in skype?
It is very uncomfortable
Please help me

**Comment by cupidarrow0417** [comment]
live:.cid.55cca203794d7a3c

**Comment by lelouchB** [comment]
Why use Postman, if you create a new account then the code should work 
Did Raw body type work ? 

I don't use Skype

**Comment by cupidarrow0417** [comment]
What about discord?

**Comment by cupidarrow0417** [comment]
The reason I use Postman is same error before

**Comment by cupidarrow0417** [comment]
Please help me.

**Comment by lelouchB** [comment]
It's late here
Will take a look and share the steps to run in Postman tomorrow

**Comment by cupidarrow0417** [comment]
Just a minute.
It will do

**Comment by cupidarrow0417** [comment]
Sometimes do and sometimes do not. What is the reason? Can you explain about that?

**Comment by lelouchB** [comment]
Must be Rate Limiting or the request taking too long that it fails

**Comment by cupidarrow0417** [comment]
Ok
Can you explain about max_tokens and temperature?
Last question

**Comment by lelouchB** [comment]
It's covered in the FreeCodeCamp tutorial

**Comment by cupidarrow0417** [comment]
Thank you for your kindness.
I wish chat with others. Please send your name on any chatting tools

**Comment by lelouchB** [comment]
I am pretty active on Twitter so we can chat there 
Username - noharashutosh

Excited to see what new features or project you build 
Please share once done
