### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'trim')

### ISSUE THREAD

**Issue by gunjan1909** [lelouchB/ai-job-description#4]

**Comment by lelouchB** [comment]
@gunjan1909 
Is there a `.env` file with the Open AI API Key ?

**Comment by gunjan1909** [comment]
> @gunjan1909 
> Is there a `.env` file with the Open AI API Key ?

Yes, and even in your hosted website there's this issue.

**Comment by lelouchB** [comment]
My deployed version will not work, the free credits were used a long time ago.

Can you share the name of the environment variable ?

**Comment by gunjan1909** [comment]
> My deployed version will not work, the free credits were used a long time ago.
> 
> Can you share the name of the environment variable ?

Name of the variable: OPENAI_API_KEY
https://github.com/gunjan1909/ai-job-description/blob/main/src/pages/api/returnJobDescription.js my code for fetching data from api

**Comment by gunjan1909** [comment]
> My deployed version will not work, the free credits were used a long time ago.
> 
> Can you share the name of the environment variable ?

In the deployed version, after clicking generate button I see the same error in console, I checked but my api key is working, is it possible for you to make changes in your code anywhere and debug if there's any issue other than the expired api credentials?

**Comment by lelouchB** [comment]
Sure
Will do

**Comment by lelouchB** [comment]
@gunjan1909 
Code is working fine, please check your API Key

**Comment by gunjan1909** [comment]
> @gunjan1909 Code is working fine, please check your API Key

![image](https://user-images.githubusercontent.com/82956298/232786531-71956560-cb5d-40ca-9e4d-cbc0c1d5adaa.png)
Your deployed site and my own site has this error.

**Comment by lelouchB** [comment]
My site has this error because my Open AI account is out of credits.

Can you check your API key. The error is because of no response from API request since the API key might be invalid

**Comment by gunjan1909** [comment]
> My site has this error because my Open AI account is out of credits.
> 
> Can you check your API key. The error is because of no response from API request since the API key might be invalid

Ok I will check with new api key. Thank you
